### PR TITLE
Remove patched interfaces

### PR DESCRIPTION
**Pull request by tsalo**
Closes None.

## Changes proposed in this pull request
- Remove DespikePatch and hardcode the output filename.
- Remove ReHoNamePatch and hardcode the output filename.

## Documentation that should be reviewed
None.

### CODE REVIEW

**Comment by tsalo** [comment]
It looks like the ReHo patch interface copies the input file, but the Despike patch doesn't. I can adapt one or more of the upstream nodes to generate shorter output filenames instead of appending to the input filenames, which should resolve the problem without requiring additional custom interfaces.

**Comment by mattcieslak** [comment]
Do you know if the directories are included in the path given as input ReHo? The directories get extremely nested sometimes, which contributed to the problem. I don't think the upstream nodes can write outside of their directories.

Maybe using CopyFile in the input spec's trait for the in file will get around the problem? I'm not sure if that still ends up including the absolute path to the input file even if it's symlinked into the sandbox directory

**Comment by tsalo** [comment]
I believe the absolute path is included in the filename, but it looks like our current patch interface doesn't account for that either. It just uses the current working directory, which should include the long path to the node's assigned working directory. I think the interface _could have_ used the basename of the copied file, since that file would be in the working directory, but it doesn't.

**Comment by mattcieslak** [comment]
The bug appeared when there are more than 256 characters in the file name. I'd test with a 1000 character filename

**Comment by tsalo** [comment]
It looks like Python has an issue with filenames longer than 256 characters, since I was getting OSErrors. I'm thinking that that means that Python is either more restrictive than, or equally restrictive as, AFNI.

**Comment by tsalo** [comment]
Paused until there's a solid reason to move forward.

**Pull request closed without merging**
