### PR TITLE
Output warped atlases to derivatives

### LINKED ISSUE #643: Copy atlases to top of derivatives folder
## Summary
I don't think the actual atlases are accessible to users at the moment, so we should add copies to the top of the xcpd output directory.

## Additional details
Users get the images and TSV files if they want to unmask/visualize their data, or even just to get relevant metadata/labels.

## Next steps
1. Add a node in the atlas-fetching workflow that checks if the atlas files exist in the output directory and, if not, copies them over.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #643.

## Changes proposed in this pull request

- Replace the copied version of DerivativesDataSink with a child class inheriting from the official niworkflows version.
- Pin niworkflows to 1.7.1.
- Add a step to downcast the CIFTI atlases to int16 (cast_cifti_to_int16), because niworkflows's DerivativesDataSink will attempt to treat dlabel.nii files as NIFTIs. Trying to set the data type of a CIFTI using the same command as one would for a NIFTI will cause an error. We circumvent that by ensuring that the files have the appropriate data type ahead of time.
- Copy atlas files to top level of xcpd derivatives folder, so users have access to the atlases. We will need to update this when we standardize our atlas format (e.g., by copying over the TSVs and JSONs as well).

## Documentation that should be reviewed
None

### CODE REVIEW

**Review by kahinimehta — APPROVED** [review]

**Comment by kahinimehta** [comment]
Might have to update the fcon tests @tsalo

**Comment by tsalo** [comment]
Note about c6c5a1e719ed3cbdcede4ddfe6dc68719bc8ca6b- our copy of DerivativesDataSink tries to coerce dseg files to int16, which fails on CIFTI files. However, the niworkflows version _should_ work on CIFTIs, so it seems like we should use that instead.

**Comment by tsalo** [comment]
It looks like DerivativesDataSink doesn't provide any way to override the default path patterns and entities, so I think I'll need to copy over the source code. Given that niworkflows was relicensed since the last time we did this, I will need to look at their licensing and see what needs to be done to incorporate modified versions of their code into xcpd.

**Comment by tsalo** [comment]
This may need to wait until https://github.com/nipreps/niworkflows/issues/757 is resolved.

**Comment by tsalo** [comment]
I should be able to use niworkflows' DerivativesDataSInk once https://github.com/nipreps/niworkflows/pull/762 is merged and a new release is made. Then we just import it, use it as a parent class for a new DerivativesDataSink, and override some of the attributes.

**Comment by tsalo** [comment]
I'm going to merge this now. I think we will need to also output the sidecar files and node labels once #551 is addressed.

**Pull request merged**
