### PR TITLE
Select BOLD files in a single space

### PR DESCRIPTION
**Pull request by tsalo**
Related to #566, #557, and #350.

## Changes proposed in this pull request

- Within `xcp_d.utils.bids.collect_data`, loop through allowed template spaces to find BOLD files in the most preferable available space, and only in that space. Also reduce to only include one resolution and density.
- Remove `select_cifti_bold`. `collect_data` now grabs only the files it will use.

## Documentation that should be reviewed
None

### CODE REVIEW

**Comment by tsalo** [comment]
This is a really kludgy way to select BOLD files in one space (ignoring different resolutions and/or densities). It loops through preferred spaces and grabs the files from the first one it finds.

**Review by kahinimehta — APPROVED** [review]

**Comment by tsalo** [comment]
I think I've got the resolutions and densities handled now 🎉

**Comment by tsalo** [comment]
We should really try testing on datasets with multiple resolutions and densities in the same space.

**Comment by tsalo** [comment]
This PR will limit support to five spaces: MNI152NLin6Asym, MNI152NLin2009cAsym, MNIInfant, fsLR, and fsaverage. I don't know if fsaverage should be supported (only when fsLR data are not available, of course). @madisoth WDYT?

**Comment by tsalo** [comment]
Dropped fsaverage, but we've added supporting it to the roadmap.

**Pull request merged**
