### PR TITLE
Create reformatted BrainSwipes figures for HBCD QC

### LINKED ISSUE #1089: Format executive summary images for BrainSwipes
## Summary
The web application https://brainswipes.us/ uses images from the executive summary.
BrainSwipes needs registrations as **.PNG** files in a **3x3** format like so:
sub-269462_ses-48mo_task-rest_run-04_desc-TaskInT2
The executive summary outputs images in a 1x9 format. It sometimes outputs .GIF files.

We request that either the existing 1x9 images are replaced with 3x3 pngs, or that the executive summary also outputs 3x3 pngs alongside the existing 1x9 images.

🧠 🧠 🧠 ✔️ 
🧠 🧠 🧠
🧠 🧠 🧠

🧠 🧠 🧠 🧠 🧠 🧠 🧠 🧠 🧠 🚫 

## Additional details
BrainSwipes is intended as the primary method of QC for HBCD outputs processed by XCPD.
For previous datasets the conversion from 1x9 to 3x3 has been handled by [a script in the brainswipes repository](https://github.com/DCAN-Labs/BrainSwipes/blob/cb2ce964bcae93c9a234e4421c07b88bcadf2908/tools/images/ingest_brainswipes_data.py#L113)

Due to the policies and architecture used by HBCD, it is not possible to use this method. 

## Next steps
The python tool above could be used. It generally runs quickly.
If there is a simple way to output images in a 3x3 format originally this may be cleaner.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #1089.

## Changes proposed in this pull request

- Add a step to restructure 1x9 figures to 3x3 for HBCD BrainSwipes QC.

### CODE REVIEW

**Comment by tsalo** [comment]
@BarryTik, it looks like the updated version is still causing problems. I can modify XCP-D's code to work off of height-width ratios instead of hardcoded pixel counts, but I need your version to include full pixel counts (e.g., `im[100:200]` instead of `im[100:]`). Would you mind adding that?

**Comment by BarryTik** [comment]
Just issued a PR [#2](https://github.com/tsalo/xcp_d/pull/2)

**Comment by tsalo** [comment]
@BarryTik sorry for the delay- had to figure out why the artifacts weren't being stored. I figured that out, but the reordered images don't look good. This is the `AtlasOnAnatBrainSwipes_T1w` from the nibabies test run:

image

**Comment by BarryTik** [comment]
Its perfect! Thanks for doing this.
Anything else you need?

**Comment by tsalo** [comment]
I don't need anything else. I'll merge now.

**Pull request merged**
