### PR TITLE
[TST] Add linting GH workflow

### PR DESCRIPTION
**Pull request by tsalo**
Related to, but does not close, #471.

## Changes proposed in this pull request

- Create a GitHub workflow that lints the `xcp_d` code.
- Use flake8, flake8-absolute-import, flake8-docstrings, flake8-isort, flake8-unused-arguments, flake8-use-fstring, flake8-warnings, and pep8-naming for the check.

## Documentation that should be reviewed

None.

### CODE REVIEW

**Comment by kahinimehta** [comment]
@tsalo Yes, might make sense - I think we had used autopep8 before

**Comment by tsalo** [comment]
Here are a few that look useful to me:

- [pep8-naming](https://github.com/PyCQA/pep8-naming), which would flag any variable/class/function/etc. names that aren't PEP8 compliant.
- [flake8-docstrings](https://github.com/pycqa/flake8-docstrings): Checks for PEP-compliant docstrings.
- [flake8-spellcheck](https://github.com/MichaelAquilina/flake8-spellcheck): Spell-checker. There are others that I've seen used, like Codespell.
- [flake8-absolute-import](https://github.com/bskinn/flake8-absolute-import): Reminds to use absolute imports instead of relative ones. 
- [flake8-use-fstring](https://github.com/MichaelKim0407/flake8-use-fstring): Reminds to use f-strings instead of `%` formatting or `.format`. 
- [flake8-unused-arguments](https://github.com/nhoad/flake8-unused-arguments): Warns about unused parameters.
- [flake8-warnings](https://github.com/orsinium-labs/flake8-warnings): Warns when using deprecated functions, classes, etc.

**Comment by kahinimehta** [comment]
Makes sense- @tsalo . Added to list.

**Comment by tsalo** [comment]
It looks like the linter flagged ~2000 issues. I'd be happy to merge this as-is and address each issue by type in future PRs.

**Pull request merged**
